export const AUDIT_MODULES = {
  AUTH: 'AUTH',
  USER: 'USER',
  ORGANIZATION: 'ORGANIZATION',
  CONTRACT: 'CONTRACT',
  PURCHASE_ORDER: 'PURCHASE_ORDER',
  CREDIT_NOTE: 'CREDIT_NOTE',
  DEBIT_NOTE: 'DEBIT_NOTE',
  PROFORMA_INVOICE: 'PROFORMA_INVOICE',
  PACKING_LIST: 'PACKING_LIST',
  COMMERCIAL_INVOICE: 'COMMERCIAL_INVOICE',
  STORAGE: 'STORAGE',
  SUBSCRIPTION: 'SUBSCRIPTION',
  PAYMENT: 'PAYMENT',
  LEGAL: 'LEGAL',
};

export const AUDIT_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
};

export const AUDIT_ACTIONS = {
  AUTH_SIGNUP: 'AUTH_SIGNUP',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_FAILED_LOGIN: 'AUTH_FAILED_LOGIN',
  AUTH_PASSWORD_CHANGE: 'AUTH_PASSWORD_CHANGE',
  AUTH_PASSWORD_RESET_REQUESTED: 'AUTH_PASSWORD_RESET_REQUESTED',
  AUTH_EMAIL_VERIFIED: 'AUTH_EMAIL_VERIFIED',
  AUTH_GOOGLE_LOGIN: 'AUTH_GOOGLE_LOGIN',
  AUTH_TOKEN_REFRESHED: 'AUTH_TOKEN_REFRESHED',

  ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
  ORGANIZATION_UPDATED: 'ORGANIZATION_UPDATED',
  ORGANIZATION_LOGO_UPLOADED: 'ORGANIZATION_LOGO_UPLOADED',

  CONTRACT_CREATED: 'CONTRACT_CREATED',
  CONTRACT_DRAFT_SAVED: 'CONTRACT_DRAFT_SAVED',
  CONTRACT_DRAFT_DELETED: 'CONTRACT_DRAFT_DELETED',
  CONTRACT_GENERATED: 'CONTRACT_GENERATED',
  CONTRACT_REVIEWED: 'CONTRACT_REVIEWED',
  CONTRACT_DOWNLOADED: 'CONTRACT_DOWNLOADED',
  CONTRACT_UPLOADED: 'CONTRACT_UPLOADED',
  CONTRACT_SIGNED_UPLOADED: 'CONTRACT_SIGNED_UPLOADED',

  PURCHASE_ORDER_CREATED: 'PURCHASE_ORDER_CREATED',
  PURCHASE_ORDER_DRAFT_SAVED: 'PURCHASE_ORDER_DRAFT_SAVED',
  PURCHASE_ORDER_DRAFT_DELETED: 'PURCHASE_ORDER_DRAFT_DELETED',
  PURCHASE_ORDER_GENERATED: 'PURCHASE_ORDER_GENERATED',
  PURCHASE_ORDER_DOWNLOADED: 'PURCHASE_ORDER_DOWNLOADED',

  CREDIT_NOTE_CREATED: 'CREDIT_NOTE_CREATED',
  CREDIT_NOTE_DRAFT_SAVED: 'CREDIT_NOTE_DRAFT_SAVED',
  CREDIT_NOTE_DRAFT_DELETED: 'CREDIT_NOTE_DRAFT_DELETED',
  CREDIT_NOTE_GENERATED: 'CREDIT_NOTE_GENERATED',
  CREDIT_NOTE_DOWNLOADED: 'CREDIT_NOTE_DOWNLOADED',

  DEBIT_NOTE_CREATED: 'DEBIT_NOTE_CREATED',
  DEBIT_NOTE_DRAFT_SAVED: 'DEBIT_NOTE_DRAFT_SAVED',
  DEBIT_NOTE_DRAFT_DELETED: 'DEBIT_NOTE_DRAFT_DELETED',
  DEBIT_NOTE_GENERATED: 'DEBIT_NOTE_GENERATED',
  DEBIT_NOTE_DOWNLOADED: 'DEBIT_NOTE_DOWNLOADED',

  PROFORMA_INVOICE_CREATED: 'PROFORMA_INVOICE_CREATED',
  PROFORMA_INVOICE_DRAFT_SAVED: 'PROFORMA_INVOICE_DRAFT_SAVED',
  PROFORMA_INVOICE_DRAFT_DELETED: 'PROFORMA_INVOICE_DRAFT_DELETED',
  PROFORMA_INVOICE_GENERATED: 'PROFORMA_INVOICE_GENERATED',
  PROFORMA_INVOICE_DOWNLOADED: 'PROFORMA_INVOICE_DOWNLOADED',

  PACKING_LIST_CREATED: 'PACKING_LIST_CREATED',
  PACKING_LIST_DRAFT_SAVED: 'PACKING_LIST_DRAFT_SAVED',
  PACKING_LIST_DRAFT_DELETED: 'PACKING_LIST_DRAFT_DELETED',
  PACKING_LIST_GENERATED: 'PACKING_LIST_GENERATED',
  PACKING_LIST_DOWNLOADED: 'PACKING_LIST_DOWNLOADED',

  COMMERCIAL_INVOICE_CREATED: 'COMMERCIAL_INVOICE_CREATED',
  COMMERCIAL_INVOICE_DRAFT_SAVED: 'COMMERCIAL_INVOICE_DRAFT_SAVED',
  COMMERCIAL_INVOICE_DRAFT_DELETED: 'COMMERCIAL_INVOICE_DRAFT_DELETED',
  COMMERCIAL_INVOICE_GENERATED: 'COMMERCIAL_INVOICE_GENERATED',
  COMMERCIAL_INVOICE_DOWNLOADED: 'COMMERCIAL_INVOICE_DOWNLOADED',

  FILE_UPLOADED: 'FILE_UPLOADED',
  FILE_DELETED: 'FILE_DELETED',
  S3_UPLOAD_SUCCESS: 'S3_UPLOAD_SUCCESS',
  S3_UPLOAD_FAILED: 'S3_UPLOAD_FAILED',

  SUBSCRIPTION_PURCHASED: 'SUBSCRIPTION_PURCHASED',
  SUBSCRIPTION_RENEWED: 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  USER_PROFILE_UPDATED: 'USER_PROFILE_UPDATED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',

  TERMS_ACCEPTED: 'TERMS_ACCEPTED',
  TERMS_ACCEPTED_POLICY_UPDATE: 'TERMS_ACCEPTED_POLICY_UPDATE',
};
